services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    networks:
      - docker-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - docker-network
  
  db:
    build: ./database
    container_name: capstone_db_container
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ab
      - POSTGRES_DB=capstone_db
    networks:
      - docker-network
    volumes:
      - db-data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
volumes:
  db-data:
networks:
  docker-network:
