import { DefaultTheme } from 'styled-components';
import { defaultTheme } from './defaultTheme';

export const christmasTheme: DefaultTheme = {
  ...defaultTheme,
  fonts: {
    ...defaultTheme.fonts,
    colour: "#FFFFFF",
    descriptor: "#EBEBEB",
  },
  background: "#1A1A1A",
  colours: {
    ...defaultTheme.colours,
    primaryLight: "#2A7A47",
    primaryDark: "#87ff8b",
    secondaryLight: "#B03A2E",
    secondaryDark: "#FF6F61",
    cancel: "#FF6F61",
    cancelDark: "#FFB3B3",
    confirmDark: "#005700",
    confirm: "#2A7A47",
    sidebarBackground: "#3D3D3D",
    optionUnselected: "#3D3D3D",
    optionSelected: "#87ff8b",
    filterText: "#EBEBEB",
    notifDate: "#87ff8b",
    notifLight: "#3D3D3D",
    notifDark: "#EBEBEB",
    progressEnd: "#A5D6A7",
    progressStart: "#FF6F61",
    progressBackground: "#EBEBEB",
    cardBackground: "#2C3A47",
  },
  themes: {
    light: "#EBEBEB",
    dark: "#333333",
    christmas: "#2A7A47",
    colourblind: "#4363D8",
  },
  teamView: {
    ...defaultTheme.teamView,
    pending: "#FF6F61",
    unregistered: "#FFEA00",
    registered: "#8BC34A",
  },
  roles: {
    ...defaultTheme.roles,
    coachText: "#EBEBEB",
    coachBackground: "#FF6F61",
    siteCoordinatorText: "#333333",
    siteCoordinatorBackground: "#8BC34A",
    adminText: "#333333",
    adminBackground: "#FFF700",
    studentText: "#C70039",
    studentBackground: "#FFB3B3",
  },
  teamProfile: {
    ...defaultTheme.teamProfile,
    invite: "#FF6F61",
    inviteBorder: "#FFB3B3",
    join: "#2A7A47",
    joinBorder: "#A5D6A7",
    name: "#e1b100",
    nameBorder: "#fff1a0",
    site: "#0073ff",
    siteBorder: "#bbdaff",
  },
  staffActions: {
    ...defaultTheme.staffActions,
    code: "#555555",
    codeBorder: "#FFFFFF",
    competition: "#FF4C4C",
    competitionBorder: "#FF6F61",
    registration: "#e1b100",
    registrationBorder: "#fff1a0",
    seat: "#0073ff",
    seatBorder: "#bbdaff",
    contact: "#9b007c",
    contactBorder: "#ffacee",
    capacity: "#2A7A47",
    capacityBorder: "#A5D6A7",
  },
};
