import { DefaultTheme } from 'styled-components';
import { defaultTheme } from './defaultTheme';

export const colourblindTheme: DefaultTheme = {
  ...defaultTheme,
  fonts: {
    ...defaultTheme.fonts,
    colour: "#FFFFFF",
    descriptor: "#A9A9A9",
  },
  background: "#000000",
  colours: {
    ...defaultTheme.colours,
    primaryLight: "#FFE119",
    primaryDark: "#4363D8",
    secondaryLight: "#F58231",
    secondaryDark: "#DCBEFF",
    cancel: "#800000",
    cancelDark: "#000075",
    confirmDark: "#A9A9A9",
    confirm: "#FFFFFF",
    sidebarBackground: "#000000",
    optionUnselected: "#A9A9A9",
    optionSelected: "#FFE119",
    filterText: "#FFFFFF",
    notifDate: "#4363D8",
    notifLight: "#A9A9A9",
    notifDark: "#FFE119",
    progressEnd: "#000075",
    progressStart: "#FFE119",
    progressBackground: "#A9A9A9",
    cardBackground: "#2C3A47",
  },
  themes: {
    light: "#EBEBEB",
    dark: "#333333",
    christmas:  "#2A7A47",
    colourblind: "#4363D8",
  },
  teamView: {
    ...defaultTheme.teamView,
    pending: "#F58231",
    unregistered: "#DCBEFF",
    registered: "#FFE119",
  },
  roles: {
    ...defaultTheme.roles,
    coachText: "#FFE119",
    coachBackground: "#4363D8",
    siteCoordinatorText: "#DCBEFF",
    siteCoordinatorBackground: "#800000",
    adminText: "#F58231",
    adminBackground: "#FFFFFF",
    studentText: "#A9A9A9",
    studentBackground: "#000000",
  },
  teamProfile: {
    ...defaultTheme.teamProfile,
    invite: "#FFE119",
    inviteBorder: "#4363D8",
    join: "#F58231",
    joinBorder: "#DCBEFF",
    name: "#A9A9A9",
    nameBorder: "#FFFFFF",
    site: "#800000",
    siteBorder: "#000075",
  },
  staffActions: {
    ...defaultTheme.staffActions,
    code: "#A9A9A9",
    codeBorder: "#FFFFFF",
    competition: "#FFE119",
    competitionBorder: "#4363D8",
    registration: "#F58231",
    registrationBorder: "#DCBEFF",
    seat: "#800000",
    seatBorder: "#FFFFFF",
    contact: "#A9A9A9",
    contactBorder: "#000075",
    capacity: "#FFE119",
    capacityBorder: "#4363D8",
  },
};
