import { DefaultTheme } from 'styled-components';

export const defaultTheme: DefaultTheme = {
  background: "#FFFFFF",
  colours: {
    primaryLight: "#BCCFF8",
    primaryDark: "#6688D2",
    secondaryLight: "#FDD386",
    secondaryDark: "#EA9C0D",
    cancel: "#F68486",
    cancelDark: "#AD0B0B",
    confirm: "#8BDFA5",
    confirmDark: "#2A7A47",
    sidebarBackground: "#EBEBEB",
    optionUnselected: "#EBEBEB",
    optionSelected: "#BCCFF8",
    filterText: "#6c757d",
    sidebarLine: "rgba(122, 122, 122, 90%)",
    staffOption: "#FEB1B1",
    error: "red",
    notifDate: "#6688D2",
    notifLight: "#EBEBEB",
    notifDark: "#333333",
    progressStart: "#283e6c",
    progressEnd: "#6688D2",
    progressBackground: "#BCCFF8",
    userInfoCardHeader: "#D6D6D6",
    cardBackground: "white",
  },
  themes: {
    light: "#EBEBEB",
    dark: "#333333",
    christmas:  "#2A7A47",
    colourblind: "#4363D8",
  },
  teamProfile: {
    invite: "#DFE8FB",
    inviteBorder: "#6688D2",
    join: "#FEEBC8",
    joinBorder: "#EA9C0D",
    name: "#FDE2FC",
    nameBorder: "#F19EDC",
    site: "#E1FAFC",
    siteBorder: "#35B4C2",
  },
  staffActions: {
    code: "#FFFFFF",
    codeBorder: "#333333",
    competition: "#DFE8FB",
    competitionBorder: "#6688D2",
    registration: "#FEEBC8",
    registrationBorder: "#EA9C0D",
    seat: "#FDE2FC",
    seatBorder: "#F19EDC",
    contact: "#E1FAFC",
    contactBorder: "#35B4C2",
    capacity: "#E8F7EC",
    capacityBorder: "#8BDFA5",
  },
  teamView: {
    pending: "#F68486",
    unregistered: "#FDD386",
    registered: "#8BDFA5",
    levelA: "#D268D1",
    levelB: "#6688D2",
  },
  roles: {
    participantBackground: '#4fdeee2b',
    participantText: '#35B4C2',
    coachText: "#6688D2",
    coachBackground: "#BCCFF8",
    siteCoordinatorText: "#9747FF",
    siteCoordinatorBackground: "#ECDCFF",
    adminText: "#D268D1",
    adminBackground: "#FDE2FC",
    studentText: "#35B4C2",
    studentBackground: "#E1FAFC",
  },
  access: {
    acceptedBackground: 'rgba(143, 238, 153, 0.30)',
    acceptedText: '#4CAF72  ',
    rejectedBackground: 'rgba(253, 102, 106, 0.30)',
    rejectedText: '#ED6A71 ',
    pendingBackground: 'rgba(253, 211, 134, 0.30)',
    pendingText: '#EA9C0D ',
  },
  fonts: {
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSizes: {
      small: "14px",
      medium: "16px",
      large: "20px",
      subheading: "24px",
      heading: "28px",
      title: "32px"
    },
    fontWeights: {
      regular: 400,
      medium: 500,
      bold: 600,
    },
    spacing: {
      normal: "0.3px",
      wide: "1px",
    },
    colour: "#000000",
    descriptor: "#333333",
    email: "blue",
    style: "italic",
  },
};


// However the default Theme is structured will be the type of the theme
// export type Theme = typeof defaultTheme;