import { SqlDbCompetitionRepository } from "../../../repository/competition/sqldb";
import pool, { dropTestDatabase } from "../Utils/dbUtils";

describe('Competition Teams Function', () => {
  let user_db;
  beforeAll(async () => {
    user_db = new SqlDbCompetitionRepository(pool);
  });

  afterAll(async () => {
    await dropTestDatabase(pool);
  });

  test('Failure case: User has no access to this list', async () => {
    const result = await user_db.competitionTeams(5, 1);
    expect(result).toStrictEqual([])
  })

  test('Sucess case: returns a list of teams in competition', async () => {
    const result = await user_db.competitionTeams(1, 1);
    expect(result).toStrictEqual([
      {
        teamId: 1,
        universityId: 2,
        status: 'Registered',
        teamNameApproved: true,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Bulbasaur',
        teamSite: 'Computer Science Building',
        teamSeat: 'Bongo11',
        teamLevel: 'Level B',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent4@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 4",
          "preferredContact": "Minecraft:EpicMan123",
          "userId": 8,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent5@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 5",
          "preferredContact": "Roblox: epicerrMan123",
          "userId": 9,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent6@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 6",
          "preferredContact": "faxMachineNumber:98531234",
          "userId": 10,
        }],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      },
      {
        teamId: 2,
        universityId: 2,
        status: 'Pending',
        teamNameApproved: false,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Charmander',
        teamSite: 'Computer Science Building',
        teamSeat: 'Tabla01',
        teamLevel: 'Level A',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "student@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "New User",
          "preferredContact": "Email:example@email.com",
          "userId": 5,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent2@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "Test Student Account 2",
          "preferredContact": "Discord:fdc234",
          "userId": 6,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent3@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "Test Student Account 3",
          "preferredContact": "Phone:0413421311",
          "userId": 7,
        },],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      },
      {
        teamId: 3,
        universityId: 2,
        status: 'Pending',
        teamNameApproved: false,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Charmeleon',
        teamSite: 'K7',
        teamSeat: 'Organ20',
        teamLevel: 'Level B',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent7@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 7",
          "preferredContact": "faxMachineNumber:98531234",
          "userId": 12,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent8@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 8",
          "preferredContact": "Phone:0402067382",
          "userId": 13,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent9@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 9",
          "preferredContact": "Email:anotherexample@email.com",
          "userId": 14,
        },],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      },
      {
        teamId: 16,
        universityId: 2,
        status: 'Unregistered',
        teamNameApproved: true,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Charizard',
        teamSite: 'Computer Science Building',
        teamSeat: 'Bongo11',
        teamLevel: 'Level A',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "ar@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "AR",
          "preferredContact": "Email:example@email.com",
          "userId": 15,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "ak@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "AK",
          "preferredContact": "Discord:fdc234",
          "userId": 16,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "yf@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "YF",
          "preferredContact": "Phone:0413421311",
          "userId": 17,
        },],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      },
      {
        teamId: 17,
        universityId: 2,
        status: 'Unregistered',
        teamNameApproved: false,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Snorlax',
        teamSite: 'K7',
        teamSeat: 'Organ20',
        teamLevel: 'Level B',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "dy@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "DY",
          "preferredContact": "Minecraft:EpicMan123",
          "userId": 18,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "kass@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Kass",
          "preferredContact": "Roblox: epicerrMan123",
          "userId": 19,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "jl@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "JL",
          "preferredContact": "faxMachineNumber:98531234",
          "userId": 20,
        }],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      }
    ])
  })

  test('Sucess case 2: Coaches has access to some list', async () => {
    const result = await user_db.competitionTeams(2, 1);
    expect(result).toStrictEqual([
      {
        teamId: 1,
        universityId: 2,
        status: 'Registered',
        teamNameApproved: true,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Bulbasaur',
        teamSite: 'Computer Science Building',
        teamSeat: 'Bongo11',
        teamLevel: 'Level B',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent4@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 4",
          "preferredContact": "Minecraft:EpicMan123",
          "userId": 8,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent5@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 5",
          "preferredContact": "Roblox: epicerrMan123",
          "userId": 9,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent6@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 6",
          "preferredContact": "faxMachineNumber:98531234",
          "userId": 10,
        }],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      },
      {
        teamId: 2,
        universityId: 2,
        status: 'Pending',
        teamNameApproved: false,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Charmander',
        teamSite: 'Computer Science Building',
        teamSeat: 'Tabla01',
        teamLevel: 'Level A',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "student@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "New User",
          "preferredContact": "Email:example@email.com",
          "userId": 5,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent2@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "Test Student Account 2",
          "preferredContact": "Discord:fdc234",
          "userId": 6,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent3@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "Test Student Account 3",
          "preferredContact": "Phone:0413421311",
          "userId": 7,
        },],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      },
      {
        teamId: 3,
        universityId: 2,
        status: 'Pending',
        teamNameApproved: false,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Charmeleon',
        teamSite: 'K7',
        teamSeat: 'Organ20',
        teamLevel: 'Level B',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent7@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 7",
          "preferredContact": "faxMachineNumber:98531234",
          "userId": 12,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent8@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 8",
          "preferredContact": "Phone:0402067382",
          "userId": 13,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "teststudent9@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Test Student Account 9",
          "preferredContact": "Email:anotherexample@email.com",
          "userId": 14,
        },],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      },
      {
        teamId: 16,
        universityId: 2,
        status: 'Unregistered',
        teamNameApproved: true,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Charizard',
        teamSite: 'Computer Science Building',
        teamSeat: 'Bongo11',
        teamLevel: 'Level A',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "ar@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "AR",
          "preferredContact": "Email:example@email.com",
          "userId": 15,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "ak@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "AK",
          "preferredContact": "Discord:fdc234",
          "userId": 16,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "yf@example.com",
          "isRemote": false,
          "level": "Level A",
          "name": "YF",
          "preferredContact": "Phone:0413421311",
          "userId": 17,
        },],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      },
      {
        teamId: 17,
        universityId: 2,
        status: 'Unregistered',
        teamNameApproved: false,
        compName: 'South Pacific Preliminary Contest 2024',
        teamName: 'Snorlax',
        teamSite: 'K7',
        teamSeat: 'Organ20',
        teamLevel: 'Level B',
        startDate: new Date('2025-09-30T00:00:00Z'),
        students: [{
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "dy@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "DY",
          "preferredContact": "Minecraft:EpicMan123",
          "userId": 18,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "kass@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "Kass",
          "preferredContact": "Roblox: epicerrMan123",
          "userId": 19,
        },
        {
          "ICPCEligible": true,
          "bio": "epic bio",
          "boersenEligible": true,
          "email": "jl@example.com",
          "isRemote": false,
          "level": "Level B",
          "name": "JL",
          "preferredContact": "faxMachineNumber:98531234",
          "userId": 20,
        }],
        coach: { name: 'Coach 1', email: 'coach@example.com', bio: 'epic bio' }
      }
    ])
  })
})