// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver';
// const assert = require('assert')

describe('Register Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register Test', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1210, height: 1040 })
    await driver.findElement(By.css("div.login--StyledFlexBackground-0 > form.login--StyledFormContainer-0 > div:nth-of-type(3) > span.login--StyledSignUpLink-0:nth-of-type(2)")).click()
    await driver.findElement(By.css("button.role-select--StyledStudentButton-0")).click()
    await driver.findElement(By.css("button.role-select--StyledButton-0")).click()
    await driver.findElement(By.css("div.account-data-input--StyledDoubleInputContainer-0 > div.text-input--StyledContainer-0 > input.text-input--StyledInput-0")).click()
    await driver.findElement(By.css("div.account-data-input--StyledDoubleInputContainer-0 > div.text-input--StyledContainer-0 > input.text-input--StyledInput-0")).sendKeys("student")
    await driver.findElement(By.css("div.account-data-input--StyledDoubleInputContainer-0 > div.text-input--StyledContainer-0:nth-of-type(2) > input.text-input--StyledInput-0")).sendKeys("lastname")
    await driver.findElement(By.css("div.account-data-input--StyledContentContainer-0 > div.text-input--StyledContainer-0:nth-of-type(2) > input.text-input--StyledInput-0")).sendKeys("preferred")
    await driver.findElement(By.css("div.account-data-input--StyledDoubleInputContainer-1:nth-of-type(3) > div.drop-down-input--StyledContainer-0 > div.drop-down-input--StyledRelativeSelectGrid-0 > select.drop-down-input--StyledRelativeSelectElement-0")).click()
    {
      const dropdown = await driver.findElement(By.css("div.account-data-input--StyledDoubleInputContainer-1:nth-of-type(3) > div.drop-down-input--StyledContainer-0 > div.drop-down-input--StyledRelativeSelectGrid-0 > select.drop-down-input--StyledRelativeSelectElement-0"))
      await dropdown.findElement(By.xpath("//option[. = 'Male']")).click()
    }
    await driver.findElement(By.css("div.account-data-input--StyledDoubleInputContainer-1:nth-of-type(3) > div:nth-of-type(2) > div.drop-down-input--StyledContainer-0 > div.drop-down-input--StyledRelativeSelectGrid-0 > select.drop-down-input--StyledRelativeSelectElement-0")).click()
    {
      const dropdown = await driver.findElement(By.css("div.account-data-input--StyledDoubleInputContainer-1:nth-of-type(3) > div:nth-of-type(2) > div.drop-down-input--StyledContainer-0 > div.drop-down-input--StyledRelativeSelectGrid-0 > select.drop-down-input--StyledRelativeSelectElement-0"))
      await dropdown.findElement(By.xpath("//option[. = 'He/Him']")).click()
    }
    await driver.findElement(By.css("div.text-input--StyledContainer-0:nth-of-type(4) > input.text-input--StyledInput-0")).click()
    await driver.findElement(By.css("div.text-input--StyledContainer-0:nth-of-type(4) > input.text-input--StyledInput-0")).sendKeys("pre@email.com")
    await driver.findElement(By.css("div.text-input--StyledContainer-0:nth-of-type(5) > input.text-input--StyledInput-0")).click()
    await driver.findElement(By.css("div.text-input--StyledContainer-0:nth-of-type(5) > input.text-input--StyledInput-0")).sendKeys("123")
    await driver.findElement(By.css("div.text-input--StyledContainer-0:nth-of-type(6) > input.text-input--StyledInput-0")).click()
    await driver.findElement(By.css("div.text-input--StyledContainer-0:nth-of-type(6) > input.text-input--StyledInput-0")).sendKeys("123")
    await driver.findElement(By.css(".account-data-input--StyledButton-1")).click()
    await driver.findElement(By.css("select.drop-down-input--StyledRelativeSelectElement-0")).click()
    {
      const dropdown = await driver.findElement(By.css("select.drop-down-input--StyledRelativeSelectElement-0"))
      await dropdown.findElement(By.xpath("//option[. = 'Mens XS']")).click()
    }
    await driver.findElement(By.css("button:nth-of-type(2)")).click()
    await driver.findElement(By.css("select.drop-down-input--StyledRelativeSelectElement-0")).click()
    {
      const dropdown = await driver.findElement(By.css("select.drop-down-input--StyledRelativeSelectElement-0"))
      await dropdown.findElement(By.xpath("//option[. = 'RMIT University']")).click()
    }
    await driver.findElement(By.css("input.text-input--StyledInput-0")).click()
    await driver.findElement(By.css("input.text-input--StyledInput-0")).sendKeys("123")
    await driver.findElement(By.css("button.institution-data-input--StyledCreateAccountButton-0:nth-of-type(2)")).click()
  })
})
